
export const sample_foods: any[] = [
  {
    id:'1',
    name: 'Italian pizza',
    price:150,
    cookTime: '20-35',
    favorite: false,
    origins: ['indian'],
    imageUrl: 'assets/italian pizza.png',
    tags: ['Pizza'],
  },
   
  {
    id:'2',
    name: 'FrenchFry',
    price:80,
    cookTime: '15-25',
    favorite: false,
    origins: ['indian'],
    imageUrl: 'assets/frenchFry.png',
    tags: ['Fry'],
  },
  {
    id:'3',
    name: 'crispyFry',
    price: 60,
    cookTime: '25-30',
    favorite: false,
    origins: ['indian'],
    imageUrl: 'assets/cryspyFry.png',
    tags: ['Fry'],
  },
  {
    id:'4',
    name: 'Gujrati Thali',
    price: 70,
    cookTime: '10-20',
    favorite: false,
    origins: ['indian'],
    imageUrl: 'assets/GujratiThali.png',
    tags: ['Lunch'],
  },
  {
    id:'5',
    name: 'Pure Gujrati Thali Lunch',
    price:100,
    cookTime: '15-25',
    favorite: false,
    origins: ['indian,Kathiyavadi dish'],
    imageUrl: 'assets/Gujaratithali.png',
    tags: ['Lunch'],
  },
  {
    id:'6',
    name: 'Pani Puri Fastfood',
    price:40,
    cookTime: '10-20',
    favorite: false,
    origins: ['indian'],
    imageUrl: 'assets/PaniPuri.png',
    tags: ['Fastfood'],
  },
  {
    id:'7',
    name: 'Burger Fastfood',
    cookTime: '10-20',
    price: 50,
    favorite: false,
    origins: ['italy'],
    imageUrl: 'assets/dish-1.png',
    tags: ['Fastfood'],
  },
  {
    id:'8',
    name: 'Momos Lunch',
    price:60,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    imageUrl: 'assets/dish-2.png',
    tags: [ 'Lunch'],
  },
  {
    id:'9',
    name: 'Bhature Fastfood',
    price:70,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
   imageUrl: 'assets/dish-3.png',
    tags: ['Fastfood'],
  },
  {
    id:'10',
    name: 'Pizza',
    price: 250,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    imageUrl: 'assets/dish-4.png',
   tags: ['Pizza'],
  },
  {
    id:'11',
    name: 'Tomato Soup',
    price:40,
    cookTime: '30-40',
    favorite: false,
    origins: ['india', 'asia'],
    imageUrl: 'assets/Tomato.png',
    tags: ['Soup'],
  },
  {
    id:'12',
    name: 'PanirTikka Lunch',
    price: 150,
    cookTime: '25-30',
    favorite: false,
    origins: ['italy'],
    imageUrl: 'assets/dish-6.png',
    tags: ['Lunch'],
  },
  {
    id:'13',
    name: 'Litti Chowkha Lunch',
    price:200,
    cookTime: '20-30',
    favorite: false,
    origins: ['Indian'],
    imageUrl: 'assets/dish-7.jpg',
   tags: ['Lunch'],
  },
  {
    id:'14',
    name: 'Pulav Bhat Lunch',
    price:80,
    cookTime: '10-30',
    favorite: false,
    origins: ['indian'],
    imageUrl: 'assets/dish-9.jpg',
    tags: ['Lunch'],
  },
  {
    id:'15',
    name: 'Italian Pizza',
    price:350,
    cookTime: '15-40',
    favorite: false,
    origins: ['indian'],
    imageUrl: 'assets/italianPizza.png',
    tags: ['Pizza'],
  },
  {
    id:'16',
    name: 'Gujrati Khichadi Lunch',
    price:60,
    cookTime: '15-40',
    favorite: false,
    origins: ['indian'],
    imageUrl: 'assets/masala_kichdi.png',
    tags: ['Lunch'],
  },{
    id:'17',
    name: 'Gujarati Dal-Bhat Lunch',
    price:70,
    cookTime: '15-40',
    favorite: false,
    origins: ['indian'],
    imageUrl: 'assets/dalbhat.png',
    tags: ['Lunch'],
  },{
    id:'18',
    name: 'Gujrati Pauva',
    price:30,
    cookTime: '15-40',
    favorite: false,
    origins: ['indian'],
    imageUrl: 'assets/pauva.png',
    tags: ['Pizza'],
  },{
    id:'19',
    name: 'Gujrati Ragda Samosa Lunch',
    price:50,
    cookTime: '15-40',
    favorite: false,
    origins: ['indian'],
    imageUrl: 'assets/samosa.png',
    tags: ['Lunch'],
  },{
    id:'20',
    name: 'Gughra Fastfood',
    price:40,
    cookTime: '15-40',
    favorite: false,
    origins: ['indian'],
    imageUrl: 'assets/gughra.png',
    tags: ['Fastfood'],
  },{
    id:'21',
    name: 'Manchurian chinese Lunch',
    price:60,
    cookTime: '15-40',
    favorite: false,
    origins: ['indian'],
    imageUrl: 'assets/manchurian.png',
    tags: ['Lunch'],
  }
]

export const sample_tags:any[] = [
  { name: 'All',count:15 },
  { name: 'Fastfood', count:3 },
  { name: 'Pizza', count:3 },
  { name: 'Lunch', count:6 },
  { name: 'Fry', count:2 },
  { name: 'Soup', count:1 },
];
